### ISSUE TITLE
xlsx file can't be read (2.0.1)

### ISSUE THREAD

**Issue by fighter777** [justkawal/excel#198] opened 2022-12-20 10:44 UTC
hello,

first, thx you for your work :)

next, i can't read a xlsx file since the last version

with a forcing in the 2.0.0-null-safety-3 version, that work

_Error: "0" can not be parsed to boolean._

ByteData data = await rootBundle.load("assets/xls/file.xlsx");
List<int> bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
var decoder = Excel.**decodeBytes**(bytes); <---

thx you :)

**Comment by rickypid** [comment] 2022-12-21 07:39
+1

**Comment by RichiB20** [comment] 2022-12-21 09:56
Same problem! Hope they can fix it.
Thank you

**Comment by guenth39** [comment] 2022-12-22 14:19
Same problem!

**Comment by xzghx** [comment] 2022-12-30 09:44
I have the same problem when calling
 `Excel excel = Excel.decodeBytes(fileBytes);`
Please solve it. I really need this package. 
Thank you

**Comment by fighter777** [comment] 2022-12-30 09:47
> I have the same problem when calling `Excel excel = Excel.decodeBytes(fileBytes);` Please solve it. I really need this package. Thank you

fix the version to 2.0.0 in your pubspec.yaml
  excel: 2.0.0-null-safety-3

**Comment by xzghx** [comment] 2022-12-30 09:55
> excel: 2.0.0-null-safety-3

Thank you so much. worked.

**Comment by justkawal** [comment] 2023-01-02 05:54
@fighter777 Can you please post the `stack-trace` of the error ?

**Comment by fighter777** [comment] 2023-01-02 10:24
> @fighter777 Can you please post the `stack-trace` of the error ?

> Error: "0" can not be parsed to boolean.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/excel/src/sheet/header_footer.dart 193:5                                                                          BoolParsing.parseBool
packages/excel/src/sheet/header_footer.dart 169:67                                                                         fromXmlElement
packages/excel/src/parser/parse.dart 696:45                                                                                [_parseHeaderFooter]
packages/excel/src/parser/parse.dart 439:5                                                                                 [_parseTable]
packages/excel/src/parser/parse.dart 160:9                                                                                 <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/core/iterable.dart 325:35                                        forEach
packages/excel/src/parser/parse.dart 158:30                                                                                [_parseContent]
packages/excel/src/parser/parse.dart 18:5                                                                                  [_startParsing]
packages/excel/src/excel.dart 74:12                                                                                        __
packages/excel/src/excel.dart 17:20                                                                                        _newExcel
packages/excel/src/excel.dart 84:12                                                                                        decodeBytes
packages/test_flutter/fonctions/load_excel.dart 119:25                                                                     loadData
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                                     callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

**Comment by justkawal** [comment] 2023-01-02 12:33
@james-d-hasselman 
Thanks for the PR you made earlier on Header and Footer.

I think that the issue is thrown when the value is `"0"` in line `169` on calling `parseBool()` from extension: https://github.com/justkawal/excel/blob/1409061f8cac7d6ff48f9d583935efe6f14b77b2/lib/src/sheet/header_footer.dart#L169

Extension: https://github.com/justkawal/excel/blob/1409061f8cac7d6ff48f9d583935efe6f14b77b2/lib/src/sheet/header_footer.dart#L186

**Comment by justkawal** [comment] 2023-01-02 12:34
@james-d-hasselman Do you think the stringified integer value is possible ?

**Comment by YancyHsu** [comment] 2023-02-04 01:51
> @james-d-hasselman Do you think the integer value is possible ?

yes, i tried this, and it works

extension BoolParsing on String {
  bool parseBool() {
    if (this.toLowerCase() == 'true') {
      return true;
    } else if (this.toLowerCase() == 'false') {
      return false;
    } else {
      return false;
    }

    throw '"$this" can not be parsed to boolean.';
  }
}

**Comment by youssefhegab14** [comment] 2023-03-05 20:29
Hello, 

Do we have an estimate time on when this bug will be fixed? Also, in the mean time do we have any workable workaround? I tried to use 2.0.0-null-safety-3 version but still experiencing the same issue.

Thanks!

**Comment by FauconSpartiate** [comment] 2023-03-06 14:29
@justkawal

**Comment by james-d-hasselman** [comment] 2023-03-07 18:24
Hi, apologies. I'll fix this before the end of today.

**Closed** 2023-03-12 06:28 UTC
Labels: bug, help wanted
