### ISSUE TITLE
Failed to parse cells of date type

### ISSUE THREAD

**Issue by kaixwdi110** [justkawal/excel#197] opened 2022-12-20 07:08 UTC
Hi justkawal,

Excel failed to parse cells of date type, for example the value "2022/11/7 10:04:46" from XLSX file will be parse to 44872.4199768519,
I find that someone had discussed this problem long ago. Have you solved it?

**Comment by AlexanderJohr** [comment] 2022-12-20 13:29
I have had this problem before but I can't reproduce it right now. Can you send the Excel file with which this problem occurs. It doesn't matter if there is a lot of other content in it. For data protection, the file should of course be pseudonymised.
If you are uncomfortable uploading the file publicly, you can also send it to my email address. It is stored in my GitHub profile.

**Comment by AlexanderJohr** [comment] 2022-12-21 13:32
A very unusual edge case indeed. In the file you sent me, the cell with the date has the format ID `numFmtId="176"`. In your style.xml file, this format is defined as a custom format:

```xml
<numFmt numFmtId="176" formatCode="yyyy\-mm\-dd\ hh:mm:ss"/>
```

However, when I open the file and save it again, Excel replaces `numFmtId="176"` with `numFmtId="168"`.
This allows the file to be read by this Dart `excel` package, as `168` is the ID for the built in date format in Excel.

Fixing the error will not be easy.

**Comment by Btan2** [comment] 2022-12-24 14:14
I have similar issues. I have to retrieve the value from the "price" column of the sheet I am working with, but instead of returning a number like 4.46 it ends up being a wackass date-time code e.g. 2000-02-01T12:03:03. The cell format code of the price column is user defined and reads as follows: "$"#,##0.00
Removing the cell format code fixes this issue, but it means I have to do that for every sheet I import...

**Comment by FauconSpartiate** [comment] 2023-01-02 11:05
Duplicate of #21

**Closed** 2023-01-02 11:05 UTC
Labels: duplicate, enhancement
