### ISSUE TITLE
Excel.decodeBytes(bytes) is blocking the UI thread

### ISSUE THREAD

**Issue by alihabbash** [justkawal/excel#110] opened 2021-08-13 08:40 UTC
I read a big Excel file about 10k rows and I use async for the function that read the file, but when it reaches `Excel.decodeBytes(bytes)` the UI thread is blocked, and the progress indicator is freezed until the method is finished its work.

**Comment by hcaz** [comment] 2021-08-23 10:21
Duplicate of #96

**Closed** 2023-01-02 10:53 UTC
