### ISSUE TITLE
delete sheet1

### ISSUE THREAD

**Issue by esingulten** [justkawal/excel#315] opened 2024-01-21 08:51 UTC
Hello dear developer, in the previous version, sheet1 was automatically created, and I used to delete sheet1. Now it's automatically created again, but I can't delete it. I get the following error:

UnmodifiableListMixin.removeWhere (dart:_internal/list.dart:139:5)
E/flutter (8393): #1 Excel.delete (package:excel/src/excel.dart:279:22)

**Comment by SebKister** [comment] 2024-01-23 01:12
Issue seems to be with 
`   _archive.files.removeWhere((file) {
        return file.name.toLowerCase() == _xmlSheetId[sheet]?.toLowerCase();
      });`
 _archive.files is an UnmodifiableListView

**Comment by amedeop** [comment] 2024-01-29 09:43
You cannot even rename it: you get the same error.

`var defaultSheet = excel.getDefaultSheet() ?? "Sheet1";`
`excel.rename(defaultSheet, "NewSheetName");`
`Error: Unsupported operation: Cannot remove from an unmodifiable list`
This is a bit strange

**Comment by lexxxel** [comment] 2024-01-29 11:42
Duplicate of https://github.com/justkawal/excel/issues/309#issuecomment-1914475812

**Comment by houdayec** [comment] 2024-02-01 20:55
#309 

Check this fix:

https://github.com/justkawal/excel/issues/309#issuecomment-1896225285

**Comment by eduardofcr** [comment] 2024-02-20 11:02
same issue here

**Closed** 2024-03-16 10:17 UTC
