### ISSUE TITLE
Is it possible to add a border to a cell?

### ISSUE THREAD

**Issue by UnexpectedCharacterAtLine96** [justkawal/excel#203] opened 2023-01-18 11:41 UTC
Hey guys,

I recognized that the styling of my excel (.xlsx) template gets lost when I import it / create the Excel Object from it so I need to add the styling at this moment manually. Is there a way to add a border to a cell?

Thanks for your help!

**Comment by FauconSpartiate** [comment] 2023-01-18 11:53
Duplicate of #32

**Closed by FauconSpartiate** 2023-01-18 11:53 UTC
Labels: duplicate, enhancement
