### ISSUE TITLE
[Feature] Set cell border

### ISSUE THREAD

**Issue by Mayb3Nots** [justkawal/excel#106] opened 2021-07-21 13:20 UTC
As the title mentions, is there a way to set the cell's border style? If not is there any plan to implement it?

**Comment by blueeyestw** [comment] 2021-07-29 03:59
bumping this thread

**Comment by ProgrammerAHM** [comment] 2021-09-13 14:44
and center content too

**Comment by FauconSpartiate** [comment] 2023-01-02 11:00
Duplicate of #32

**Closed** 2023-01-02 11:01 UTC
Labels: duplicate, enhancement
