### ISSUE TITLE
Border Deleted After Save

### ISSUE THREAD

**Issue by Pairs34** [justkawal/excel#199] opened 2022-12-31 18:51 UTC
![resim](https://user-images.githubusercontent.com/34889012/210153123-087868f0-257d-4d8e-8cb9-612b552f6bca.png)

Hello, I open an excel file from the assets folder, change the cells and save it and the borders disappear.

Like this , 

![resim](https://user-images.githubusercontent.com/34889012/210153162-7fab3aea-7165-4c67-acd5-1a6d518b1bf9.png)

How can I resolve it ?

`ByteData data = await rootBundle.load("assets/F041.xlsx");
              var bytes = data.buffer
                  .asUint8List(data.offsetInBytes, data.lengthInBytes);
              var excel = Excel.decodeBytes(bytes);

              excel.updateCell(
                  "F41", CellIndex.indexByString("C11"), "Ali YILDIRIM");

              List<int>? fileBytes = excel.save();

              var directory = await getExternalStorageDirectory();

              if (directory != null && fileBytes != null) {
                File("${directory.path}/exported.xlsx")
                  ..createSync(recursive: true)
                  ..writeAsBytesSync(fileBytes);`

[F041.xlsx](https://github.com/justkawal/excel/files/10327853/F041.xlsx)

**Comment by FauconSpartiate** [comment] 2023-01-02 10:59
Duplicate of #32

**Closed** 2023-01-02 11:00 UTC
Labels: duplicate, enhancement
